# Generated by Django 2.2 on 2019-06-07 20:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(choices=[('Car', 'Car'), ('Bus', 'Bus')], default='Car', max_length=64)),
                ('category', models.CharField(choices=[('Mini Car', 'Mini Car'), ('Economy Car', 'Economy Car'), ('Standerd Car', 'Standerd Car'), ('Luxury Car', 'Luxury Car'), ('SUV Car', 'SUV Car'), ('7 Seat Car', '7 Seat Car'), ('Permium Car', 'Permium Car'), ('Luxury Coachs Bus', 'Luxury Coachs Bus'), ('Mini Coaches Bus', 'Mini Coaches Bus'), ('Mini Vans Bus', 'Mini Vans Bus')], default='Mini Car', max_length=64)),
                ('is_automatic', models.BooleanField(default=True)),
                ('passengers', models.IntegerField(default=5)),
                ('year', models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2013)),
                ('photo', models.ImageField(blank=True, upload_to='model')),
                ('introduction', models.TextField(blank=True, max_length=256, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model', to='vehicle.Brand')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_plate_no', models.CharField(max_length=16, unique=True)),
                ('exp_date', models.DateField()),
                ('is_actived', models.BooleanField(default=True, verbose_name='Active')),
                ('avg_score', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='company.Company')),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='vehicle.Model')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='ModelPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary', models.CharField(max_length=128)),
                ('full_day', models.BooleanField(default=False)),
                ('cost_price', models.DecimalField(decimal_places=2, default=600.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('gross_price', models.DecimalField(decimal_places=2, default=800.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price', to='vehicle.Model')),
            ],
            options={
                'verbose_name': 'Model Price',
                'verbose_name_plural': 'Model Prices',
            },
        ),
    ]
