# Generated by Django 2.2 on 2019-04-20 16:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itinerary', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'Car'), (1, 'Bus')], default=0)),
                ('category', models.IntegerField(choices=[(0, 'Mini Car'), (1, 'Economy Car'), (2, 'Standerd Car'), (3, 'Luxury Car'), (4, 'SUV Car'), (5, '7 Seat Car'), (6, 'Permium Car'), (7, 'Luxury Coachs Bus'), (8, 'Mini Coaches Bus'), (9, 'Mini Vans Bus')], default=0)),
                ('is_automatic', models.BooleanField(default=True)),
                ('passengers', models.IntegerField(default=5)),
                ('photo', models.ImageField(blank=True, upload_to='model')),
                ('introduction', models.TextField(blank=True, max_length=256, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model', to='vehicle.Brand')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_plate_no', models.CharField(max_length=16, unique=True)),
                ('exp_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='company.Company')),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='vehicle.Model')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='ItineraryPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, default=600.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('gross_price', models.DecimalField(decimal_places=2, default=800.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_price', to='itinerary.Itinerary')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_price', to='vehicle.Model')),
            ],
            options={
                'verbose_name': 'ItineraryPrice',
                'verbose_name_plural': 'ItineraryPrices',
            },
        ),
    ]
