# Generated by Django 2.2 on 2019-06-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelprice',
            old_name='cost_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='modelprice',
            name='gross_price',
        ),
    ]
