# Generated by Django 2.2 on 2019-04-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_active',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_actived',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
