# Generated by Django 2.2 on 2019-06-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprice',
            name='itinerary',
            field=models.CharField(max_length=128),
        ),
    ]
