# Generated by Django 2.2 on 2019-05-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
        ('vehicle', '0002_auto_20190428_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItineraryPrice',
            new_name='ModelPrice',
        ),
        migrations.AlterModelOptions(
            name='modelprice',
            options={'verbose_name': 'Model Price', 'verbose_name_plural': 'Model Prices'},
        ),
    ]
