# Generated by Django 2.2 on 2019-05-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20190523_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='category',
            field=models.CharField(choices=[('Mini Car', 'Mini Car'), ('Economy Car', 'Economy Car'), ('Standerd Car', 'Standerd Car'), ('Luxury Car', 'Luxury Car'), ('SUV Car', 'SUV Car'), ('7 Seat Car', '7 Seat Car'), ('Permium Car', 'Permium Car'), ('Luxury Coachs Bus', 'Luxury Coachs Bus'), ('Mini Coaches Bus', 'Mini Coaches Bus'), ('Mini Vans Bus', 'Mini Vans Bus')], default='Mini Car', max_length=64),
        ),
        migrations.AlterField(
            model_name='model',
            name='type',
            field=models.CharField(choices=[('Car', 'Car'), ('Bus', 'Bus')], default='Car', max_length=64),
        ),
    ]
