# Generated by Django 2.2 on 2019-05-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20190523_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='total_score',
        ),
    ]
