# Generated by Django 2.2 on 2019-05-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20190508_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprice',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='itinerary.Itinerary'),
        ),
        migrations.AlterField(
            model_name='modelprice',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price', to='vehicle.Model'),
        ),
    ]
