# Generated by Django 2.2 on 2019-05-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20190524_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='avg_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
