# Generated by Django 2.2 on 2019-05-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20190508_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelprice',
            old_name='itinerary',
            new_name='itiner',
        ),
    ]
