# Generated by Django 2.2 on 2019-05-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20190521_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelprice',
            name='itiner',
        ),
        migrations.AddField(
            model_name='modelprice',
            name='is_fullday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelprice',
            name='itinerary',
            field=models.CharField(default='dubai city tour', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
