# Generated by Django 2.2 on 2019-05-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20190525_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelprice',
            old_name='is_fullday',
            new_name='full_day',
        ),
    ]
