# Generated by Django 2.2 on 2019-06-01 07:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=128)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('expiry_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Disscount',
                'verbose_name_plural': 'Disscounts',
            },
        ),
    ]
