# Generated by Django 2.2 on 2019-05-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='exp_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='uuid',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
