# Generated by Django 2.2 on 2019-05-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_auto_20190508_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='exp_date',
            new_name='expiry_date',
        ),
    ]
