# Generated by Django 2.2 on 2019-06-07 20:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('charge_status', models.CharField(choices=[('not-charged', 'Not charged'), ('partially-charged', 'Partially charged'), ('fully-charged', 'Fully charged'), ('partially-refunded', 'Partially refunded'), ('fully-refunded', 'Fully refunded')], default='not-charged', max_length=20)),
                ('token', models.CharField(blank=True, default='', max_length=128)),
                ('total_currency', djmoney.models.fields.CurrencyField(choices=[('AED', 'AED €'), ('CNY', 'CNY ￥'), ('USD', 'USD $')], default='AED', editable=False, max_length=3)),
                ('total', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('captured_amount_currency', djmoney.models.fields.CurrencyField(choices=[('AED', 'AED €'), ('CNY', 'CNY ￥'), ('USD', 'USD $')], default='AED', editable=False, max_length=3)),
                ('captured_amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('currency', models.CharField(max_length=10)),
                ('extra_data', models.TextField(blank=True, default='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.Order')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
