# Generated by Django 2.2 on 2019-05-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='last_change',
        ),
    ]
