# Generated by Django 2.2 on 2019-04-21 16:38

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='captured_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AED', 'UAE Dirham'), ('USD', 'US Dollar'), ('CNY', 'Yuan Renminbi')], default='AED', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AED', 'UAE Dirham'), ('USD', 'US Dollar'), ('CNY', 'Yuan Renminbi')], default='AED', editable=False, max_length=3),
        ),
    ]
