# Generated by Django 2.2 on 2019-04-21 16:41

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190421_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='captured_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AED', 'AED €'), ('CNY', 'CNY ￥'), ('USD', 'USD $')], default='AED', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AED', 'AED €'), ('CNY', 'CNY ￥'), ('USD', 'USD $')], default='AED', editable=False, max_length=3),
        ),
    ]
