# Generated by Django 2.2 on 2019-06-20 08:05

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190620_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='captured_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('AED', 'AED'), ('USD', 'USD'), ('CNY', 'CNY')], default='AED', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
    ]
