# Generated by Django 2.2 on 2019-06-01 08:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingId', models.CharField(editable=False, max_length=64)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('contact_name', models.CharField(max_length=64)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('pick_up_addr', models.CharField(blank=True, max_length=128, null=True, verbose_name='Pick up address')),
                ('drop_off_addr', models.CharField(blank=True, max_length=128, null=True, verbose_name='Drop off address')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('change_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Process', 'Process'), ('Complete', 'Complete'), ('Cancel', 'Cancel'), ('Delete', 'Delete')], default='Created', max_length=16)),
                ('remark', models.TextField(blank=True, max_length=256, null=True)),
                ('vehicle_score', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('guide_score', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comment', models.TextField(blank=True, max_length=256, null=True)),
                ('company_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='company.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('itinerary', models.CharField(max_length=128)),
                ('full_day', models.BooleanField(default=False)),
                ('freedom_day', models.BooleanField(default=False)),
                ('vehicle_cost_charge', models.DecimalField(decimal_places=2, default=600.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('vehicle_gross_charge', models.DecimalField(decimal_places=2, default=800.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('guide_charge', models.DecimalField(decimal_places=2, default=400.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('remark', models.CharField(blank=True, max_length=256, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='booking.Booking')),
            ],
            options={
                'verbose_name': 'Itinerary',
                'verbose_name_plural': 'Itinerarys',
            },
        ),
    ]
