# Generated by Django 2.2 on 2019-04-30 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('is_freedom_day', models.BooleanField(default=False, verbose_name='Freedom Day?')),
                ('remark', models.CharField(blank=True, max_length=256, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='booking.Booking')),
                ('itinerary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary', to='itinerary.Itinerary')),
            ],
            options={
                'verbose_name': 'Itinerary',
                'verbose_name_plural': 'Itinerarys',
            },
        ),
    ]
