# Generated by Django 2.2 on 2019-06-07 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190601_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order'),
        ),
    ]
