# Generated by Django 2.2 on 2019-06-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190608_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmId',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
