# Generated by Django 2.2 on 2019-04-30 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190430_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
