# Generated by Django 2.2 on 2019-06-20 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_confirmid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='guide_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
