# Generated by Django 2.2 on 2019-06-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190607_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Complete', 'Complete'), ('Cancel', 'Cancel')], default='Created', max_length=16),
        ),
    ]
