# Generated by Django 2.2 on 2019-05-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190523_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='chanage_at',
            new_name='change_at',
        ),
    ]
