# Generated by Django 2.2 on 2019-06-22 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190620_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='company_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='company.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_customer', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
    ]
