# Generated by Django 2.2 on 2019-06-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20190622_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='vehicle_cost_charge',
            new_name='vehicle_charge',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='vehicle_gross_charge',
        ),
    ]
