# Generated by Django 2.2 on 2019-06-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20190627_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='order',
        ),
    ]
