# Generated by Django 2.2 on 2019-05-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20190523_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_comment',
        ),
    ]
