# Generated by Django 2.2 on 2019-05-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_is_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='expiry_date',
        ),
    ]
