# Generated by Django 2.2 on 2019-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_booking_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Cancel', 'Cancel'), ('Delete', 'Delete'), ('Process', 'Complete'), ('Complete', 'Complete')], default='Created', max_length=16),
        ),
    ]
