# Generated by Django 2.2 on 2019-04-30 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20190430_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
