# Generated by Django 2.2 on 2019-04-30 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20190430_1713'),
        ('booking', '0010_booking_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='primary_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='order.Order'),
        ),
    ]
