# Generated by Django 2.2 on 2019-05-01 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20190430_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='arrival_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='departure_time',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='primary_order',
        ),
        migrations.AddField(
            model_name='booking',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
