# Generated by Django 2.2 on 2019-05-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20190501_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='discount_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='is_freedom_day',
        ),
    ]
