# Generated by Django 2.2 on 2019-05-08 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20190508_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='change_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
