# Generated by Django 2.2 on 2019-05-08 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_auto_20190508_1439'),
        ('booking', '0015_booking_change_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='discount.Discount'),
        ),
    ]
