# Generated by Django 2.2 on 2019-05-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_booking_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Darft', 'darf'), ('Confirm', 'confirm'), ('Cancel', 'cancel'), ('Delete', 'delete')], default='Darft', max_length=16),
        ),
    ]
