# Generated by Django 2.2 on 2019-05-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'darf'), (1, 'confirm'), (2, 'cancel'), (3, 'delete')], default=0),
        ),
    ]
