# Generated by Django 2.2 on 2019-05-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20190516_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='level',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Cancel', 'Cancel'), ('Delete', 'Delete')], default='Created', max_length=16),
        ),
    ]
