# Generated by Django 2.2 on 2019-05-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20190520_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='change_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
