# Generated by Django 2.2 on 2019-05-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_auto_20190520_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='change_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='create_at',
        ),
    ]
