# Generated by Django 2.2 on 2019-05-21 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20190521_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary', to='vehicle.ModelPrice'),
        ),
    ]
