# Generated by Django 2.2 on 2019-05-22 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_auto_20190521_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=600.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='gross_price',
            field=models.DecimalField(decimal_places=2, default=800.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='itinerary',
            field=models.CharField(max_length=128),
        ),
    ]
