# Generated by Django 2.2 on 2019-05-22 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_auto_20190522_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='charge',
            new_name='vehicle_charge',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='guide_charge',
            field=models.DecimalField(decimal_places=2, default=400.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
