# Generated by Django 2.2 on 2019-05-23 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_auto_20190522_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='booking.Booking'),
        ),
    ]
