# Generated by Django 2.2 on 2019-05-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_auto_20190523_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='booking.Booking'),
        ),
    ]
