# Generated by Django 2.2 on 2019-05-23 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_auto_20190523_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='vehicle_charge',
            new_name='vehicle_gross_charge',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='freedom_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='full_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='vehicle_cost_charge',
            field=models.DecimalField(decimal_places=2, default=600.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
