# Generated by Django 2.2 on 2019-04-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='guide_price',
        ),
    ]
