# Generated by Django 2.2 on 2019-06-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AddField(
            model_name='permission',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
