# Generated by Django 2.2 on 2019-05-08 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
        ('company', '0002_auto_20190508_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='discount.Discount'),
        ),
    ]
