# Generated by Django 2.2 on 2019-06-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190601_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('Supplier', 'Supplier'), ('Customer', 'Customer')], default='Supplier', max_length=16),
        ),
    ]
