# Generated by Django 2.2 on 2019-04-20 16:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('remark', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.TimeField()),
                ('checkout_time', models.TimeField(blank=True, default=None, null=True)),
                ('checkin_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkout_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkout_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkin_picture', models.ImageField(blank=True, null=True, upload_to='task/%Y/%m/%d')),
                ('checkout_picture', models.ImageField(blank=True, null=True, upload_to='task/%Y/%m/%d')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='order.Order')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='task.Task')),
            ],
            options={
                'verbose_name': 'Task Progress',
                'verbose_name_plural': 'Task Progress',
            },
        ),
        migrations.CreateModel(
            name='TaskPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Vehicle'), (1, 'Guide')], default=0)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='order.Order')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='task.Task')),
            ],
            options={
                'verbose_name': 'Task Price',
                'verbose_name_plural': 'Task Prices',
            },
        ),
    ]
