# Generated by Django 2.2 on 2019-04-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_taskprice_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskprogress',
            options={'verbose_name': 'Task Progress', 'verbose_name_plural': 'Task Progreses'},
        ),
    ]
