# Generated by Django 2.2 on 2019-04-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20190424_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskprogress',
            options={'verbose_name': 'Task Progress', 'verbose_name_plural': 'Task Progress'},
        ),
        migrations.AddField(
            model_name='taskprice',
            name='type',
            field=models.IntegerField(choices=[(0, 'Vehicle'), (1, 'Guide')], default=0),
        ),
    ]
