# Generated by Django 2.2 on 2019-04-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20190420_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskprice',
            name='discount_value',
        ),
    ]
