# Generated by Django 2.2 on 2019-04-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_taskprice_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskId',
            field=models.CharField(default=1, editable=False, max_length=64),
            preserve_default=False,
        ),
    ]
