# Generated by Django 2.2 on 2019-04-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20190424_1634'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('day', 'guide'), name='unique_day_guide'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('day', 'vehicle'), name='unique_day_vehicle'),
        ),
    ]
