# Generated by Django 2.2 on 2019-04-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskId',
            field=models.CharField(default=None, editable=False, max_length=64, null=True),
        ),
    ]
