# Generated by Django 2.2 on 2019-04-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20190427_1920'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_day_guide',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_day_vehicle',
        ),
        migrations.AddField(
            model_name='task',
            name='is_freedom_day',
            field=models.BooleanField(default=False, verbose_name='Freedom Day?'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('day', 'guide', 'is_freedom_day'), name='unique_day_guide'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('day', 'vehicle', 'is_freedom_day'), name='unique_day_vehicle'),
        ),
    ]
