# Generated by Django 2.2 on 2019-04-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20190421_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
