# Generated by Django 2.2 on 2019-05-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20190428_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskprice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='taskprice',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskprogress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='taskprogress',
            name='task',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskPrice',
        ),
        migrations.DeleteModel(
            name='TaskProgress',
        ),
    ]
