# Generated by Django 2.2 on 2019-04-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20190421_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_fullday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
