# Generated by Django 2.2 on 2019-04-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_is_fullday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='itinerary.Itinerary'),
        ),
    ]
