# Generated by Django 2.2 on 2019-06-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20190601_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
