# Generated by Django 2.2 on 2019-05-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
