# Generated by Django 2.2 on 2019-06-02 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190601_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='permissions',
            new_name='permission',
        ),
    ]
