# Generated by Django 2.2 on 2019-05-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190523_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_score',
        ),
    ]
