# Generated by Django 2.2 on 2019-05-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190524_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avg_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
