# Generated by Django 2.2 on 2019-06-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190602_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='index',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='name',
            new_name='label',
        ),
    ]
