# Generated by Django 2.2 on 2019-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='introduction',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
