# Generated by Django 2.2 on 2019-06-07 20:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Cancel', 'Cancel'), ('Complete', 'Complete')], default='Created', max_length=16)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('vehicle', models.CharField(max_length=128)),
                ('guide', models.CharField(blank=True, max_length=128, null=True)),
                ('customer', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('remark', models.TextField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
