# Generated by Django 2.2 on 2019-04-20 16:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(editable=False, max_length=64)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Padding'), (2, 'Cancel'), (3, 'Complete')], default=0)),
                ('pick_up_addr', models.CharField(max_length=128)),
                ('drop_off_addr', models.CharField(max_length=128)),
                ('contact_name', models.CharField(max_length=64)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('change_at', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField(blank=True, max_length=256, null=True)),
                ('link', models.URLField(blank=True, default='')),
                ('customer_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='name')),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='phone')),
                ('customer_company', models.CharField(blank=True, max_length=128, null=True, verbose_name='company')),
                ('customer_company_phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='company phone')),
                ('customer_company_tel', models.CharField(blank=True, max_length=128, null=True, verbose_name='company tel')),
                ('customer_company_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='company address')),
                ('customer_company_discount', models.CharField(blank=True, max_length=128, null=True, verbose_name='company discount')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=3, null=True)),
            ],
        ),
    ]
