# Generated by Django 2.2 on 2019-05-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Cancel', 'Cancel'), ('Complete', 'Complete'), ('Delete', 'Delete')], default='Created', max_length=16)),
                ('remark', models.TextField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.CharField(default=None, editable=False, max_length=64, null=True)),
                ('day', models.DateField()),
                ('is_freedom_day', models.BooleanField(default=False, verbose_name='Freedom Day?')),
                ('itinerary', models.CharField(max_length=128)),
                ('remark', models.CharField(blank=True, max_length=256, null=True)),
                ('checkin_time', models.TimeField(blank=True, default=None, null=True)),
                ('checkout_time', models.TimeField(blank=True, default=None, null=True)),
                ('checkin_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkout_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkout_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkin_picture', models.ImageField(blank=True, null=True, upload_to='task/%Y/%m/%d')),
                ('checkout_picture', models.ImageField(blank=True, null=True, upload_to='task/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
