# Generated by Django 2.2 on 2019-06-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
