# Generated by Django 2.2 on 2019-04-24 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0001_initial'),
        ('order', '0002_order_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='end_time',
            new_name='arrival_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='start_time',
            new_name='departure_time',
        ),
        migrations.AddField(
            model_name='order',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='vehicle.Vehicle'),
        ),
        migrations.AlterField(
            model_name='order',
            name='drop_off_addr',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pick_up_addr',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
