# Generated by Django 2.2 on 2019-04-20 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190420_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_name',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, editable=False, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
