# Generated by Django 2.2 on 2019-06-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Cancel', 'Cancel'), ('Complete', 'Complete')], default='Created', max_length=16),
        ),
    ]
