# Generated by Django 2.2 on 2019-04-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190425_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
