# Generated by Django 2.2 on 2019-04-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190420_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.CharField(default=None, editable=False, max_length=64, null=True),
        ),
    ]
