# Generated by Django 2.2 on 2019-04-27 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190427_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='create_by',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_create_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
