# Generated by Django 2.2 on 2019-04-29 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190427_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_of_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Padding'), (4, 'Cancel'), (5, 'Complete')], default=0),
        ),
    ]
