# Generated by Django 2.2 on 2019-04-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20190429_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (2, 'Padding'), (1, 'Confirm'), (3, 'Cancel'), (4, 'Complete')], default=0),
        ),
    ]
