# Generated by Django 2.2 on 2019-05-01 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('itinerary', '0001_initial'),
        ('vehicle', '0002_auto_20190428_1654'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0011_auto_20190430_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.CharField(default=None, editable=False, max_length=64, null=True)),
                ('day', models.DateField()),
                ('is_freedom_day', models.BooleanField(default=False, verbose_name='Freedom Day?')),
                ('remark', models.CharField(blank=True, max_length=256, null=True)),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to=settings.AUTH_USER_MODEL)),
                ('itinerary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='itinerary.Itinerary')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='arrival_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='departure_time',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='change_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_company_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_company_discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_company_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_company_tel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drop_off_addr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='link',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pick_up_addr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_of_expiry',
        ),
        migrations.RemoveField(
            model_name='order',
            name='update_by',
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='company.Company'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_guide', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.TimeField()),
                ('checkout_time', models.TimeField(blank=True, default=None, null=True)),
                ('checkin_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkout_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkout_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('checkin_picture', models.ImageField(blank=True, null=True, upload_to='task/%Y/%m/%d')),
                ('checkout_picture', models.ImageField(blank=True, null=True, upload_to='task/%Y/%m/%d')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='order.Order')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='order.Task')),
            ],
            options={
                'verbose_name': 'Task Progress',
                'verbose_name_plural': 'Task Progress',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='order.Order'),
        ),
        migrations.AddField(
            model_name='task',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='vehicle.Vehicle'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('day', 'guide', 'is_freedom_day'), name='unique_day_guide'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('day', 'vehicle', 'is_freedom_day'), name='unique_day_vehicle'),
        ),
    ]
