# Generated by Django 2.2 on 2019-05-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20190501_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Padding'), (2, 'Cancel'), (3, 'Complete'), (4, 'Close')], default=0),
        ),
    ]
