# Generated by Django 2.2 on 2019-05-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20190508_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Padding', 'Padding'), ('Cancel', 'Cancel'), ('Complete', 'Complete'), ('Delete', 'Delete')], default='Open', max_length=16),
        ),
    ]
