# Generated by Django 2.2 on 2019-05-21 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20190516_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='applyId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='task',
            name='checkin_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='checkin_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='checkin_picture',
            field=models.ImageField(blank=True, null=True, upload_to='task/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='task',
            name='checkin_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='checkout_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='checkout_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='checkout_picture',
            field=models.ImageField(blank=True, null=True, upload_to='task/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='task',
            name='checkout_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Cancel', 'Cancel'), ('Complete', 'Complete'), ('Delete', 'Delete')], default='Created', max_length=16),
        ),
        migrations.DeleteModel(
            name='TaskProgress',
        ),
    ]
