# Generated by Django 2.2 on 2019-05-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_auto_20190521_1116'),
        ('order', '0020_auto_20190521_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='discount.Discount'),
        ),
    ]
