# Generated by Django 2.2 on 2019-05-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20190521_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='itinerary',
            field=models.CharField(default='dubai city tour', max_length=128),
            preserve_default=False,
        ),
    ]
